<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pizzaria</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.6.3/css/foundation.min.css">
    <link rel="stylesheet" href="<?= PATH . 'style/style.css' ?>">
</head>
<style>
    .grid-x.img-navbar {
        margin: 20px 0px;
    }

    .grid-container.fluid {
        padding: 0px;
    }

    .grid-x.nav-header {
        background-color: rgb(186, 0, 0);
        height: 64px;
        border-radius: 5px;
        position: relative;
        z-index: 1;
    }

    .grid-x.nav-header .menu ul li {
        display: inline-block;
        line-height: 64px;
        font-weight: 400;
        color: white;
        margin-right: 5px;
        font-size: 14px;
        font-family: RubikB;
    }

    div.img-menu {
        width: 250px;
        height: 152px;
        background-color: grey
    }

    div.banner-primary {
        background-image: url("<?= PATH ?>imgs/pizza.jpg");
        height: 740px;
        padding: 0px;
        margin: 0px;
        background-position: center;
        background-size: cover;
        background-repeat: no-repeat;
        margin-top: -32px;
        position: relative;
        z-index: 0;
    }

    .grid-x.align-center-middle.desc-banner h1 {
        font-family: Tiza;
        font-size: 50px;
        text-shadow: 12px 15px 14px black;
        color: white;
    }

    .grid-x.align-center-middle.desc-banner h1 span {
        font-size: 20px;
    }

    .grid-x.align-center-middle.desc-banner p {
        font-family: Rubik;
        color: white;
        font-size: 20px;
        margin-top: 30px;
    }

    .grid-x.align-center-middle.desc-banner div {
        max-width: 600px;
        text-align: center;
    }

    .button {
        font-family: RubikB;
        background-color: rgb(186, 0, 0);
    }
    div.box .box-content{
        background-color: #890125;
        height: 600px;
        width: 90%;
        border-radius: 20px;
        margin-top: -100px;
        position: relative;
    }
</style>

<body>
    <header class="grid-container fluid">
        <nav class="grid-container nav-bar">
            <div class="grid-x img-navbar" style="justify-content: center">
                <div class="img-menu">

                </div>
            </div>
            <div class="grid-x align-center nav-header">
                <div class="menu">
                    <ul class="menu-list">
                        <li class="item-list">HOME</li>
                        <li class="item-list">SOBRE PIZZARIA</li>
                        <li class="item-list">NOSSO MENU</li>
                        <li class="item-list">COMPRE AGORA</li>
                        <li class="item-list">NOVIDADES</li>
                        <li class="item-list">CONTATO</li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="grid-container fluid banner-primary">
            <div class="grid-container" style="height: 100%">
                <div class="grid-x align-center-middle desc-banner" style="height: 100%">
                    <div>
                        <h1><span>Melhor pizza de FOZ</span></h1>
                        <h1>PIZZA MEGA SPAN</h1>
                        <p>Peça a melhor pizza de foz no conforto da sua residência. Ligue ou faça você mesmo seu pedido online...</p>
                        <button class="button">FAZER MEU PEDIDO</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="grid-container fluid box">
            <div class="grid-container">
                <div class="grid-x align-center">
                    <div class="box-content">

                    </div>
                </div>
            </div>
        </div>
    </header>














    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.6.3/js/foundation.min.js"></script>
    <script src="<?= PATH ?>js/script.js"></script>
    <script>
        $(document).foundation();
    </script>
</body>

</html>